### ISSUE TITLE
very much bugs

### ISSUE THREAD

**Issue by nguyenhuuhanhlam** [codaxy/cx-getting-started#3]
Uncaught Error: Cannot find module "cx/app/startAppLoop"
Module not found: Error: Can't resolve 'cx/ui/HtmlElement'
...
and more more bugs

**Comment by mstijak** [comment]
Thanks for bringing this up. We forgot about this repository and didn't apply some of the latest changes.
This should be fixed now. Please reopen this issue if you encounter any other problem.
